name: CI

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest
      
    - name: Notify on failure
      if: failure()
      run: |
          echo "Build failed for branch ${{ github.ref }} of ${{ github.repository }}." 
          # You can add further steps here to notify via email, Slack, or other means.

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
